a= []
a.append(10)
print(a)

b= ['a', 'b', 'c']
b.append('d')
print(b)

line_up = []
line_up.append('거북이')
line_up.append('홍학')
line_up.append('토끼')
print(line_up)

c= [1, 2, 4, 5]
c.insert(2, 3)
print(c)

line_up.insert(1, '도도새')
print(line_up)

d= [3, 1, 2, 3]
d.remove(3)
print(d)

line_up.remove('도도새')
print(line_up)

a= [6,2,4,1]
a.sort()
print(a)

b = ['carrot', 'apple', 'banana']
b.sort()
print(b)

line_up.sort()
print(line_up)
